services:
  app:
    build:
      context: .
      secrets:
        - npmrc
    ports:
      - "3000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

secrets:
  npmrc:
    file: ~/.npmrc
