services:
  api:
    build:
      context: './docker/api'
    ports:
      - '6060:6060'
    networks:
      - app-network
  app:
    build:
      context: .

    ports:
      - '8000:80'
    networks:
      - app-network
    env_file: 
      - ./docker/.env.docker
    depends_on:
      - api

networks:
  app-network:
    driver: bridge
