/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainTransactionsRouteImport } from './routes/_main/transactions'
import { Route as MainHistoryRouteImport } from './routes/_main/history'

const MainSettingsLazyRouteImport = createFileRoute('/_main/settings')()
const MainBillsLazyRouteImport = createFileRoute('/_main/bills')()
const MainAnalyticsLazyRouteImport = createFileRoute('/_main/analytics')()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsLazyRoute = MainSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings.lazy').then((d) => d.Route),
)
const MainBillsLazyRoute = MainBillsLazyRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => MainRoute,
} as any).lazy(() => import('./routes/_main/bills.lazy').then((d) => d.Route))
const MainAnalyticsLazyRoute = MainAnalyticsLazyRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/analytics.lazy').then((d) => d.Route),
)
const MainTransactionsRoute = MainTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/transactions.lazy').then((d) => d.Route),
)
const MainHistoryRoute = MainHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => MainRoute,
} as any).lazy(() => import('./routes/_main/history.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/history': typeof MainHistoryRoute
  '/transactions': typeof MainTransactionsRoute
  '/analytics': typeof MainAnalyticsLazyRoute
  '/bills': typeof MainBillsLazyRoute
  '/settings': typeof MainSettingsLazyRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/history': typeof MainHistoryRoute
  '/transactions': typeof MainTransactionsRoute
  '/analytics': typeof MainAnalyticsLazyRoute
  '/bills': typeof MainBillsLazyRoute
  '/settings': typeof MainSettingsLazyRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/_main/history': typeof MainHistoryRoute
  '/_main/transactions': typeof MainTransactionsRoute
  '/_main/analytics': typeof MainAnalyticsLazyRoute
  '/_main/bills': typeof MainBillsLazyRoute
  '/_main/settings': typeof MainSettingsLazyRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/history'
    | '/transactions'
    | '/analytics'
    | '/bills'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/history'
    | '/transactions'
    | '/analytics'
    | '/bills'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/login'
    | '/_main/history'
    | '/_main/transactions'
    | '/_main/analytics'
    | '/_main/bills'
    | '/_main/settings'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bills': {
      id: '/_main/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof MainBillsLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/analytics': {
      id: '/_main/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof MainAnalyticsLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/transactions': {
      id: '/_main/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof MainTransactionsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/history': {
      id: '/_main/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof MainHistoryRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainHistoryRoute: typeof MainHistoryRoute
  MainTransactionsRoute: typeof MainTransactionsRoute
  MainAnalyticsLazyRoute: typeof MainAnalyticsLazyRoute
  MainBillsLazyRoute: typeof MainBillsLazyRoute
  MainSettingsLazyRoute: typeof MainSettingsLazyRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainHistoryRoute: MainHistoryRoute,
  MainTransactionsRoute: MainTransactionsRoute,
  MainAnalyticsLazyRoute: MainAnalyticsLazyRoute,
  MainBillsLazyRoute: MainBillsLazyRoute,
  MainSettingsLazyRoute: MainSettingsLazyRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
