/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'

const MainSettingsLazyRouteImport = createFileRoute('/_main/settings')()
const MainAnalyticsLazyRouteImport = createFileRoute('/_main/analytics')()
const MainAboutLazyRouteImport = createFileRoute('/_main/about')()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsLazyRoute = MainSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/settings.lazy').then((d) => d.Route),
)
const MainAnalyticsLazyRoute = MainAnalyticsLazyRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => MainRoute,
} as any).lazy(() =>
  import('./routes/_main/analytics.lazy').then((d) => d.Route),
)
const MainAboutLazyRoute = MainAboutLazyRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRoute,
} as any).lazy(() => import('./routes/_main/about.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/about': typeof MainAboutLazyRoute
  '/analytics': typeof MainAnalyticsLazyRoute
  '/settings': typeof MainSettingsLazyRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof MainAboutLazyRoute
  '/analytics': typeof MainAnalyticsLazyRoute
  '/settings': typeof MainSettingsLazyRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/_main/about': typeof MainAboutLazyRoute
  '/_main/analytics': typeof MainAnalyticsLazyRoute
  '/_main/settings': typeof MainSettingsLazyRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/login' | '/about' | '/analytics' | '/settings' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/about' | '/analytics' | '/settings' | '/'
  id:
    | '__root__'
    | '/_main'
    | '/login'
    | '/_main/about'
    | '/_main/analytics'
    | '/_main/settings'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/analytics': {
      id: '/_main/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof MainAnalyticsLazyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutLazyRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainAboutLazyRoute: typeof MainAboutLazyRoute
  MainAnalyticsLazyRoute: typeof MainAnalyticsLazyRoute
  MainSettingsLazyRoute: typeof MainSettingsLazyRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAboutLazyRoute: MainAboutLazyRoute,
  MainAnalyticsLazyRoute: MainAnalyticsLazyRoute,
  MainSettingsLazyRoute: MainSettingsLazyRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
