name: Deploy to Firebase
on:
  release:
    types: [published]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          pnpm config set '//npm.pkg.github.com/:_authToken' ${{ secrets.NPM_TOKEN }} 
          pnpm install

      - name: Build
        run: npm run build
        env:
          VITE_DOMAIN: ${{ secrets.DOMAIN }}
          VITE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          VITE_API_SECRET: ${{ secrets.API_SECRET }}
          VITE_API_URL: ${{ vars.API_URL }}
          VITE_AMQP_URL: ${{ secrets.AMQP_URL }}
          VITE_AMQP_VHOST: ${{ secrets.AMQP_VHOST }}
          VITE_AMQP_USER: ${{ secrets.AMQP_USER }}
          VITE_AMQP_PASSWORD: ${{ secrets.AMQP_PASSWORD }}
          

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MONTHLY_CONTROL }}
          channelId: live
          projectId: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECTID }}
